### ISSUE TITLE
Solution needed for checking the available countries/populations in HMD.

### ISSUE THREAD

**Issue by mpascariu** [mpascariu/MortalityLaws#1]
Solution needed for checking the available countries/populations in HMD.

If a new country is added in the database availableHMD() function fails to find it, because I haven't found an elegant method to read all the country codes.
No problem with the codes that I already know that are there.

Let me know if you have a solution. Thanks.
Marius

**Comment by timriffe** [comment]
The HMD makes a csv available with meta data, and for which no log-in is required. It's ugly and takes some decoding, but in principle it is rebuilt with each trivial update of the database, and it contains all info required to know which data products are available for each country, and also which date ranges:
[link](https://www.mortality.org/countries.csv)
This object is used by the `HMDHFDplus` package for this purpose. see `getHMDcountries()`

**Comment by mpascariu** [comment]
Excellent. This is neat. Thanks @timriffe, I was not aware of its existence.

**Comment by timriffe** [comment]
protip # 2: there is are 2 new files in `~/STATS/` : `mltper_1x1.csv`, and `fltper_1x1.csv`. These are different in 2 way from the standard `.txt` versions: 1) values are not rounded, 2) deaths and exposures are included as lifetable columns.

**Comment by mpascariu** [comment]
Thanks, Tim. 
The `ReadHMD()` was added in the package some time ago just to have a quick way to download data, and use it to replicate the examples for other populations (without relying on other packages).  It does not intent to necessarily cover  all the possible options in HMD. For that I think `HMDHFDplus` would be that way to go.
