### ISSUE TITLE
a0 decision rule if no sex given

### ISSUE THREAD

**Issue by alysonvanraalte** [mpascariu/MortalityLaws#10]
Should the a0 assumption not default to "total" in the case that no sex is specified? As is, the result is rather close to a midpoint in the interval.
Here are some example data:

```
library(MortalityLaws)
mx <- c(0.00439, 0.00016, 0.00009, 0.00012, 0.00023, 0.00031, 0.00036, 
0.00047, 0.00065, 0.00095, 0.00148, 0.00243, 0.00374, 0.0058, 
0.00893, 0.01444, 0.02383, 0.04183, 0.07672, 0.14308, 0.2426, 
0.37998, 0.53975, 0.67115)
x  <- c(0,1,seq(5,110,5))

# no sex specified:
LT1 <- LifeTable(mx=LT$mx,x=LT$Age)
# sex given as total:
LT2 <- LifeTable(mx=LT$mx,x=LT$Age, sex = "total")

LT1$lt$ax[1]
LT2$lt$ax[1]
```
Thanks! Alyson & Tim

**Comment by mpascariu** [comment]
Hi Alyson & Tim,

If `sex` is specified the `ax` is estimated using the Coale-Demeny coefficients. See the function ```coale.demeny.ax``` in [here](https://github.com/mpascariu/MortalityLaws/blob/master/R/LifeTable.R).

If no `sex` is specified we are estimating a point in the age internal where 50% of the deaths have already occurred. See the function `compute.ax` in the same script. This was the original solution, the C-D approach was added at a later stage.

**Comment by mpascariu** [comment]
I will add clarifications in the documentation of what happens when `sex = NULL`.
