### ISSUE TITLE
case handling

### ISSUE THREAD

**Issue by timriffe** [mpascariu/MortalityLaws#15]
There are some places where we determine action based on class:

` if (K$iclass == "numeric") {` inside `MortalityLaw()`, where the value of `iclass` comes from `find.my.case()`. The below code comes from a `DemoTools` example that previously didn't throw warnings. Now class of `mx_matrix` will return as `c("matrix" ,"array" )`, so we have a length warning in the above check. However, the following situations might also not behave as desired. 1) is a normal case. 2) used to not throw warnings, but now does. 3) throws no warning, but might not be handled properly. 4) warns and might not be handled properly. I'm not sure about the potential mishandling, though, as perhaps those calls are picked up elsewhere or downstream. If you tell me a potential better strategy I may be able to make a usable PR. So far my PR makes case (3) succeed where it used to error, but these appear to be related loose ends.

```
mx1 <- c(.0070, .0082, .0091, .0096, .0108, .0122, .0141, .0150, .0165, .0186,
         .0205, .0229, .0259, .0294, .0334, .0379, .0426, .0482, .0550, .0628,
         .0716, .0806, .0897, .1003, .1149, .1264, .1558, .1563, .1812, .2084,
         .2298, .2536, .2813, .3143, .3352, .3651, .4128)
x1 <- 65:101

# 1 works fine
MortalityLaw(x =x1, mx = mx1, law = 'makeham')

# 2) try for matrix of inputs
mx_matrix <- matrix(rep(mx1, 3), ncol = 3) %*% diag(c(1, 1.05, 1.1))
dimnames(mx_matrix) <- list(age = x1, year = c("year1", "year2", "year3"))

MortalityLaw(x =x1, mx = mx_matrix, law = 'makeham') # warns

# 3)
# no warning, BUT, we have something that should be treated as a numeric vector, but class evaluates as array, so it won't execute that code. dput() will create output like this sometimes...or always?
mx1.1  <- structure(mx1, .Dim = length(mx1))
MortalityLaw(x =x1, mx = mx1.1 , law = 'makeham')

# 4)
# 1-column matrix should be treated as numeric vector, no?, but here we get the same warning as the 2d case above
MortalityLaw(x =x1, mx =as.matrix(mx1) , law = 'makeham')
```

**Comment by mpascariu** [comment]
Interesting. I'll have a look.
At the first try I can see that if we `use as.data.frame(mx_matrix)` no warning will be shown for cases 2) and 4).

**Comment by mpascariu** [comment]
the warnings are dealt with in `v1.8.9`. All the example above should be fine now. thanks tim.
will send to cran in a week or two, just to have a few days more to re-read the code.
