### ISSUE TITLE
Issues Faced When Modeling and Forecasting Using Heligman Pollard

### ISSUE THREAD

**Issue by Wilsonnn245** [mpascariu/MortalityLaws#18]
Hi, I'm facing some issues when fitting and forecasting using the HP model as I'm still new to using R:

1. I'm unable to generate a plot of the fitted values and its parameters. These are the codes I'm using:
![image](https://user-images.githubusercontent.com/127125706/228029235-b85567d9-8fa2-4353-bd94-b9b00da3283c.png)

And its output:
![image](https://user-images.githubusercontent.com/127125706/228029403-73262a9d-67b5-46ff-9908-4403e8552e71.png)
![image](https://user-images.githubusercontent.com/127125706/228029476-6282613a-cd8e-4583-99ce-52e26c79dd91.png)

For reference, I'm looking for something like this when plotting the HP parameters:
![image](https://user-images.githubusercontent.com/127125706/228029714-112f9d51-3526-462a-b74d-d5bf132951dd.png)

2. From the users' guide, there's an explanation to extrapolate the fitted values to the older ages. However, there's no mention of using the package to forecasting using the HP model. Are the forecasting methods not included in the package? If so, how should I code using R to forecast the mortality rates using HP model? I've read in a past research that they forecast each of the parameter using ARIMA model and plug the values into the HP model to get the forecasted rates, or is there a more suitable forecasting method, please advice. 

Appreciate your help on the matter, thanks in advance :)

**Comment by mpascariu** [comment]
1. As you can see in the error message the plot functionality is not offered for objects containing multiple calibrations. It's just a limitation of the package. Fit one model at the time if a standard plot is needed.
2. Forecasting methods are not included in the package. If you really want to work with the H-P mortality model, time-series methods like ARIMA or multivariate ARMA models for forecasting coefficients might work. Give it a try and let us know what you discover 🤠
