### ISSUE TITLE
Using MortalityLaws to Model ASDR According to Age-Groups

### ISSUE THREAD

**Issue by Wilsonnn245** [mpascariu/MortalityLaws#19]
Hi Marius,

I've noticed that the package will use Heligman-Pollard to generate the 8 parameters and then generate the ASDR for every ages by substituting back the parameter values with x = age level. 
However, I'm currently modeling ASDR according to age-groups (0, 1-4, 5-9, 10-14, 15-19 etc). And thus, when using the package I would have to rename the age column to the first age of every age group (0, 1, 5, 10 etc) so that R would be able to read. I'm wondering I should make some modification to the codes if I'm modeling ASDR according to age-groups or just using the package as it is would be fine, since it might seem that the fitted values generated would be the mortality rate for the age levels instead of the age groups. 

Also, I tried to generate the AIC and BIC criterion with my current work but it returns 'NA'. I'm not sure what's the issue
![image](https://user-images.githubusercontent.com/127125706/228330675-27f235e9-94ba-4f7a-af28-084d7747ddc5.png)
Here's the code, might to be a long-winded procedure, it's because I'm trying to be as close to how the data are framed in the Introduction manual provided:
![image](https://user-images.githubusercontent.com/127125706/228331043-637e098e-cf2e-43bd-a244-4e0c30175eff.png)

Appreciate your input on the matter. Thanks!

**Comment by mpascariu** [comment]
If you modify the code you would need to find a numerical way to show the age-range your group corresponds to. A 'character' vector wont work. My easiest suggestion is to use an age level from each interval, say the middle of each age group and to assume a constant mortality within the interval. Looking forward to your solution. 

`AIC` and `BIC` values are computed only if you calibrate the model using the maximum likelihood methods as a likelihood estimate is required to derive the criterions. That is `poissonL` or `binomialL`. If other loss functions are employed no AIC is derived and NA is returned.
