### ISSUE TITLE
Appears expected life years (ex) calculation using wrong denominator in LifeTable.core method

### ISSUE THREAD

**Issue by marc-outins** [mpascariu/MortalityLaws#2]
Below is the code snippet in questions from LifeTable.R of the LifeTable.core method:

`Tx    <- rev(cumsum(rev(Lx)))`
`ex    <- Tx/(lx - dx*(ax/nx))`

Here Tx is the sum of person-years lived from the current row on down and ex should be the expected total life years lived for a person starting that row.  It looks like you are dividing by the current row's person-years lived instead of the number of people who started the interval.  

US life tables use the people starting the interval as the denominator.  I apologize if I'm missing something.

**Comment by mpascariu** [comment]
@marc-outins You're right, e(x) should be calculated at the beginning of the age interval. I guess I tried different versions when I started this package and I missed to indicate what I was doing. It is updated now in GitHub and it will be changed in CRAN too with the next submission. Thanks for noticing this.
