### ISSUE TITLE
Formulas

### ISSUE THREAD

**Issue by SheilaDesanze** [mpascariu/MortalityLaws#9]
Hi!

I got a question about gompertz's formula:

You wrote: 

"
> Table 1: Parametric functions build in the MortalityLaws package
> Mortality laws
> 
> Predictor
> 
> Gompertz
> 
> µ(x) = AeBx
> 
> Gompertz
> 
> Code
> 
> µ(x) = σ1 exp
> 
 "

Did you mean that gompertz formula is:   µ(x) = A * B^x  (Parameter "A" multiplied parameter "B" raised to "X" (X being age)  , or would you define it another way ?

I also have doubts about how the formulas of Makeham and Thiele are for you, and based on what formulas are made the codes that return the parameters.

BTW, thanks for building and share a package about biometrics!

I hope you can read me soon,
Sheila

**Comment by mpascariu** [comment]
Hi @SheilaDesanze,

You are also right, Gompertz published the law as ```mu(x) = A*B^x```, but the most popular form in literature is ```mu(x) = A * exp(bx)``` where ``` B = exp(b)```, if you want ```B``` as in the original formula.  ```x``` is the age vector. Two version of the Gompertz formula are included in the package, each having their own advantages.

Please be more specific about Makeham and Thiele in a separate issue.
Thanks!

**Comment by SheilaDesanze** [comment]
I have another question: 
when you defined the function bring_parameters why do you set values? ​​for example in gompertz A = 0.0002 and B = 0.13.  When I run the function based on the mortality table I want to evaluate, it only returns those parameters to me and does not return me parameters based on the my sample (my table).  I also see several NA values in my output.

I attached you screenshot of my output.
![Uploading 20191121_175143.png…]()


Maybe I didn't really understand how to estimate parameters for my table with your package.  **What should I run to have the parameters of gompertz according to my mortality table?**

Thanks!

**Comment by mpascariu** [comment]
To fit **any** model to your data please use the ```MortalityLaw``` function. There are a couple of examples provided in the help page ```?MortalityLaw``` and the vignette. 

The ```bring_parameters``` function brings the starting parameters in the optimization process.

**Comment by Ramzi198** [comment]
Hello,
i'm working on makeham law, i have a age vector and an qx vector, i want to fit it with the makeham model
the fitted values brings by the MortalityLaw() function are good and close to my original qx vector, but, the problem is with the  mu[x], when i calculate my mu[x] withe Makeham model: mu[x] = A exp[Bx] + C and when i want to pass  from mu[x] to qx  i dont get the same values, and clearly qx result from transformation of mu[x] to qx are greater than the fitted values returned dirctly by 
MortalityLaw() function,

**Comment by mpascariu** [comment]
Hi @Ramzi198, please provide a reproducible example here and I look into it.

**Comment by Ramzi198** [comment]
Hi
here is a part of my data frame with ages and qx of hoem:
#---------------#
homme_2=data.frame(age_homme=c(32,33,34,35,36,37,38,39,40,41),

 qx_hoem=c(0.001015622,0.0009880797,0.0009694389,0.001155229,0.001333844,0.001321422,0.001508097,
                             0.001505369,0.001698246,0.001696985))
fg<-MortalityLaw(x=homme_2$age_homme, qx=homme_2$qx_hoem,
law='makeham',opt.method = 'poissonL' )
co<-coef(fg)
homme_2<-mutate(homme_2,qx_makeham_fitted_by_mortaliyt=fitted(fg))#---values
returned by MortalityLaw--#
homme_2<-mutate(homme_2,ux_makeham_calculet_with_coeficient=(co[1]*exp(co[2]*age_homme))+co[3])#---ux
calculated with the coefficients returned by MortalityLaw
homme_2<-mutate(homme_2,

qx_makeham_ca1=ux_makeham_calculet_with_coeficient/1+ux_makeham_calculet_with_coeficient)#---qx=ux/1+ux
#--------------#
the problem that i can't reach the values of qx fitted directly by the
MortalityLaw from mu[x] calculated with the coefficient
and clearly this qu[x] resulting are greater and the qx of fitted values

thank you in advance

**Comment by mpascariu** [comment]
In the fitting of the mortality model over an age range the `MortalityLaw()` function scaled down the age vector in order to obtain meaningful estimates/ parameters of the model. So and age vector, say `32:41` becomes `1:10`. It is what we would normal do when fitting a linear model too.

In your example, if you cant to get the fitted value from the obtained coefficient we can do:
```r

> #---values returned by MortalityLaw--#
> 
> homme_2<-mutate(homme_2,
+                 age_fit = age_homme - 31,
+                 ux_makeham_calculet_with_coeficient = (co[1]*exp(co[2] * age_fit))+co[3])
> 
> homme_2
   age_homme      qx_hoem qx_makeham_fitted_by_mortaliyt ux_makeham_calculet_with_coeficient age_fit qx_makeham_ca1
1         32 0.0010156220                   0.0009545943                        0.0009545943       1    0.001909189
2         33 0.0009880797                   0.0010198889                        0.0010198889       2    0.002039778
3         34 0.0009694389                   0.0010903610                        0.0010903610       3    0.002180722
4         35 0.0011552290                   0.0011664210                        0.0011664210       4    0.002332842
5         36 0.0013338440                   0.0012485120                        0.0012485120       5    0.002497024
6         37 0.0013214220                   0.0013371123                        0.0013371123       6    0.002674225
7         38 0.0015080970                   0.0014327380                        0.0014327380       7    0.002865476
8         39 0.0015053690                   0.0015359461                        0.0015359461       8    0.003071892
9         40 0.0016982460                   0.0016473379                        0.0016473379       9    0.003294676
10        41 0.0016969850                   0.0017675623                        0.0017675623      10    0.003535125
```

I think this is what you were looking for.

**Comment by Ramzi198** [comment]
Thank you so much sir,
 that fix the problem, it a problem of index and  and I was thinking that
the values fitted returned by the MortalityLaw function was a qx, as I
passed to it a qx vector, anyway thank you very much
